##                                                                                   ##
##         _       ______   _______   _______   _    _    _____      __  __          ##
##        | |     |  __  | |__   __| |__   __| | |  | |  / ____|    /  \/  \         ##
##        | |     | |  | |    | |       | |    | |  | |  | |_      |  _  _  |        ##
##        | |     | |  | |    | |       | |    | |  | |  \____ \    \ \\// /         ##
##        | |____ | |__| |    | |       | |    | |__| |    ___| |    \ \/ /          ##
##        |_____/ |______|    |_|       |_|    |______|  |_____/      \__/           ##
##                                                                                   ##
##                      -------------------------------------                        ##
##                        Plugin created by Black_Lottus.                            ##
##                      -------------------------------------                        ##

####################################################
###            CONFIGURATION VERSION             ###
####################################################
#This version is the configuration version, not the plugin version.
#Don't edit this if you don't know what are you doing!
version: 1.5.1 ALPHA


####################################################
###               STORAGE SETTINGS               ###
####################################################
#Available storages: mysql, file
#Defaults always get the file storage!
storage-mode: file

mysql-database:
  host: 127.0.0.1
  port: 3306
  database: staff
  username: Black
  password: black_lottus

####################################################
###                GENERAL OPTIONS               ###
####################################################
titles:
  collect-head:
    enable: true
    title: "&4&l• &f&lLucky&4&lHeads &f&l•"
    subtitle: "&AEnhorabuena! &fHas encontrado una cabeza de la suerte."
  add-head:
    enable: true
    title: "&4&l• &f&lLucky&4&lHeads &f&l•"
    subtitle: "&fHas agregado al sistema una nueva cabeza."

broadcasts:
  collect-head:
    enable: true
    message: "&a%player% &fha encontrado la &bLuckyHead &fnum&e %id%"
  remove-head:
    enable: true
    message: "&fSe ha eliminado a todos los usuarios la cabeza con id &a%id%"
  add-head:
    enable: true
    message: "&fSe ha agregado una nueva cabeza con id &a%id%&f. ¿Qué esperas para buscarla?"


####################################################
###                  PERMISSIONS                 ###
####################################################
permissions:
  admin: "luckyheads.admin"
  collect: "luckyheads.collect"