name: Heads
version: '${project.version}'
main: me.black_lottus.heads.Heads
authors: [ Black_Lottus ]
description: Plugin to find heads and save data!
commands:
  heads:
    usage: /<command>
    description: Run heads commands

