name: LuckyHeads
version: '${project.version}'
api-version: 1.16
main: me.black_lottus.luckyheads.LuckyHeads
authors: [ Black_Lottus ]
description: Plugin to find heads and save data!
commands:
  luckyheads:
    usage: /<command>
    description: Run heads commands
    aliases: [lh, luckyheads]

